plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    mavenLocal()
    gradlePluginPortal()
    mavenCentral()
    maven { url = 'https://repo.spongepowered.org/maven' }
}

dependencies {
    implementation('org.spongepowered:mixingradle:0.7-SNAPSHOT') {
        transitive = false
    }
    implementation 'com.google.guava:guava:31.1-jre'
    implementation 'org.ow2.asm:asm:9.9.1'
    implementation 'org.ow2.asm:asm-tree:9.9.1'
}
